# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['sistema_financeiro_v14.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'numpy._core',
        'numpy._core._multiarray_umath',
        'numpy._core._exceptions',
        'numpy._core._dtype',
        'numpy._core._methods',
        'numpy._core.multiarray',
        'numpy._core.umath',
        'numpy.core._multiarray_umath',
        'numpy.core._dtype_ctypes',
        'numpy.linalg._umath_linalg',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.backends.backend_agg',
        'PIL',
        'PIL._tkinter_finder',
        'pandas',
        'sqlite3',
        'datetime',
        'calendar',
        'openpyxl',
        'tkcalendar',
        'psycopg2',
        'psycopg2.extensions',
        'psycopg2.extras',
        'requests',
        'requests.adapters',
        'requests.exceptions',
    ],
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='sistema_financeiro_v14',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
